$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: python -c "print('✅ Training Job Placeholder Executed'); print('Model: BERT Multi-task'); print('Accuracy: 85%'); print('MAE: 118')"
environment: azureml:viral-env:3
compute: azureml:gpu-cluster
display_name: viral-predictor-training
experiment_name: viral-prediction
description: Placeholder training job for CI/CD validation
