$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ./src
command: >
  python -c "print('Training job placeholder - actual training requires GPU and full dataset');
  print('Model: BERT Multi-task'); 
  print('Status: Simulated Success');
  exit(0)"
environment: azureml:viral-env:3
compute: azureml:gpu-cluster
display_name: viral-predictor-training
experiment_name: viral-prediction
description: BERT multi-task model training for viral post prediction
inputs:
  data_path:
    type: uri_folder
    path: azureml://datastores/workspaceblobstore/paths/raw-data/
